### ISSUE TITLE
All custom songs have infinite spinner icon

### ISSUE THREAD

**Issue by romanalexander** [Kylemc1413/SongCore#10]
I get an infinite spinner icon every other BeatSaber launch. Sometimes Custom Levels shows up fine, sometimes it fails to load. I've tried reinstalling all plugins, removing all levels and deleting UserData. Maybe a concurrency issue?

It seems to stem from 
[CRITICAL @ 23:01:41 | UnityEngine] CustomPreviewBeatmapLevel+<GetPreviewAudioClipAsync>d__57.MoveNext () (at <26ec787945bf43e5aae4af5dd3394845>:0)

Full log files:
https://gist.github.com/romanalexander/a41401ab3992a8777c97da6d1efe8bf6
https://gist.github.com/romanalexander/629df5d4d37ee0edaf2f852d601460f2

Also put the same issue in [here.](https://github.com/halsafar/BeatSaberSongBrowser/issues/94) Wasn't sure which plugin this could come from.

**Comment by Futuremappermydud** [comment]
probably mapping extensions

**Comment by Kylemc1413** [comment]
I'd try doing a clean reinstall of your game 
https://bsmg.wiki/support#clean-installation
That problem seems unrelated to songcore or songbrowser, it's possible you have corrupted files in your game installation or appdata folder for the game

**Comment by romanalexander** [comment]
I'm not sure what combination of deletions I did but the problem seems to have gone away.

Thanks!
