### ISSUE TITLE
Base game color overrides take priority over map colors

### ISSUE THREAD

**Issue by PnfrlEnm** [Kylemc1413/SongCore#119]
Map colors no longer work properly if a player has a custom color scheme set in the player settings. I can't tell if this is a bug due to adding separate toggles for notes, lights, and obstacles or if this is intended behavior, but it renders these toggles completely useless if the player has a custom color scheme (which like 95% of people do). If this _is_ a feature (please god i hope it isn't) there should be a setting to revert back to the old behavior of map set colors always taking priority

**Comment by ModdingPink** [comment]
https://github.com/Kylemc1413/SongCore/pull/122
Base Game colours will now be handled like SongCore colours and will have full feature parity

**Comment by Meivyn** [comment]
There's a clear indication when the map uses custom colors. If they *don't* want to use your color scheme, I don't see why SongCore should enforce it. If you *really* want to force it, you should use Chroma, which is more designed about map "experiences". Player would then have to disable all Chroma effects to get rid of it.
