### ISSUE TITLE
[Suggestion] If no lighting events are present on a map, enable static lights

### ISSUE THREAD

**Issue by TheBlackParrot** [Kylemc1413/SongCore#132]
Currently, if no lighting events are placed in a map, the player is simply dropped into a never-ending black void if the player doesn't enable static lights. Forcing the lights on for those who have static lights off will make it just a bit more comfortable, especially if they don't know where to find the setting.

**Comment by Meivyn** [comment]
Base game seems to do this by default now, at least I cannot reproduce that behavior on the latest version.
