### ISSUE TITLE
[Bug] User defined WIP folders are broken on 1.35

### ISSUE THREAD

**Issue by anothershad** [Kylemc1413/SongCore#137]
SongCore v3.13.0, title. Any maps that are contained in extra folders in folders.xml fail to load with an "Error loading data" error. Map was tested in editor, by moving to the standard CustomWIPLevels folder, and on 1.34.2 and the map works and loads fine in all scenarios. Tested with the following folder directory: 

```  <folder>
    <Name>Beat Saber New Editor</Name>
    <Path>F:\BSNewEditor</Path>
    <Pack>1</Pack>
    <WIP>True</WIP>
    <ImagePath>Example</ImagePath>
  </folder>
```

![image](https://github.com/Kylemc1413/SongCore/assets/122078713/c5c62fdd-94a6-4795-9c27-d23ec402e3f6)

**Comment by Meivyn** [comment]
Thanks for pointing it out shad, looks like I might have cached the beatmap data before all the levels were actually loaded.
