### ISSUE TITLE
Not possible to create custom pack and exclude it from the main pack

### ISSUE THREAD

**Issue by CodeStix** [Kylemc1413/SongCore#14]
I am trying to create a song pack, but exclude it from the main pack.
`main custom levels pack`
`custom pack`
In my custom pack folder, duplicates of original songs are made + new gamemode. The problem is that the main custom levels pack is spammed by duplicates that are in the other pack.

**Is there any possibility to hide the custom pack's songs from the main pack?**  
Maybe add a property like `<ExcludeFromMain>True</ExcludeFromMain>` to the `folders.xml` file?
Or is this unintended behaviour?

**Comment by Kylemc1413** [comment]
I don't believe separate folders specified to be new packs are intended to also load into the main collection, does this behavior persist if you do a full refresh of songs (Ctrl+R) after the initial load?

**Comment by CodeStix** [comment]
I checked it and the (Ctrl+R) does fix the problem immediately. It takes like a quater of a second to do the full refresh (Ctrl+R), maybe add a call to full refresh at startup or something?

**Comment by Kylemc1413** [comment]
I'd rather fix the problem at the source instead of do a rough fix, I'll see if I notice anything amiss next time I'm working on SongCore, or if someone can point me to where in the mod the issue is

**Comment by DonTrolav** [comment]
Just put up a pull request to fix that.
