### ISSUE TITLE
Boost colour lights are removed when disabling custom song colour scheme

### ISSUE THREAD

**Issue by qqrz997** [Kylemc1413/SongCore#146]
if you disable a map's own colour scheme, you are not using your own colour overrides, and the map uses boost colours, then any boost colour lights don't show up - probably because they're using a completely transparent colour.

in the base game if you use boost colours on a colour scheme that doesn't have boost colours set it will default to the non-boost colours, so the lights aren't invisible.

if this is intentional let me know.

**Comment by qqrz997** [comment]
title might be a bit misleading but i tried to word this as best i could

**Comment by Meivyn** [comment]
Can you link a map on which you noticed this issue?

**Comment by qqrz997** [comment]
[donut hole](https://beatsaver.com/maps/11c74) is the map i noticed it on, boost is used during the chorus around the minute mark

**Comment by Meivyn** [comment]
Can you show me a video of what you mean? I still cannot reproduce with this map. Lights should be off?

**Comment by qqrz997** [comment]
yes this is with songcore from beatmods on 1.36.2

[with songcore](https://streamable.com/5jber2) the lights go invisible

[in vanilla](https://streamable.com/gc4p57) they use the primary colours when there aren't any in use - panic environment uses "the first" colour scheme

**Comment by Meivyn** [comment]
Okay I was able to reproduce it, thanks for showing it. It happens when you disable the environment colors but keep note colors on. I'll look at it.
