### ISSUE TITLE
Load only ~100 custom songs

### ISSUE THREAD

**Issue by SpartanPlume** [Kylemc1413/SongCore#16]
Hello,

First thing first, I run Beat Saber on Linux and I installed the mod with QBeat.

The issue is that when I have a lot of custom songs, it seems there is a cap at ~100 (was 103 the first time, after reinstall 100).

After my first installation of Beat Saber, I used QBeat and added the mod and everything was working well even after downloading songs with the BeatSaverDownloader mod. (I had like ~20 custom songs)
Then I downloaded a lot of maps manually and added them and that's when I saw this issue.
After that, I did clean reinstall of the game and put the custom songs back in the folder. All the custom songs where present when unmodded. Then I installed BSIPA and used the custom Proton from QBeat, everything was still working. And when I added SongCore, there appeared the limitation.

Also, the songs loaded are the same each time (I didn't find the difference between both installation even though there were 3 songs of difference), I don't know what is the logic behind but it's neither by song name nor folder name.

If I delete a folder of a custom song that is loading in game, it doesn't load another song to replace it (so it loads 99 custom songs). And if I readd it, it loads it again.

And to finish, the songs I downloaded before and even the base custom songs (`Beat Saber` and `One More Time`) are not appearing in the list of loaded songs.

If you need me to test something to have more info, don't hesitate.

**Comment by Kylemc1413** [comment]
You have a corrupt song folder halting loading

**Comment by SpartanPlume** [comment]
Indeed, that was the problem. Thanks for your fast answer.

I think it would be better that it handles corrupted folder correctly though. Some propositions:
1) Move the corrupted folders in another folder to easily find them and to not reprocess them each time.
2) Just skip the corrupted folders
3) Delete the corrupted folders
4) Put a message below the number of loaded songs that there is a corruption
5) Add a small FAQ in the README to say that if not all songs are loaded, there is a corruption

Personally, I think a mix between 1 and 4 would be the best.

This is just a proposition though, you do what you want. ^^

**Comment by MaverickMartyn** [comment]
How would you suggest one should go about finding out which song is corrupted?
