### ISSUE TITLE
[Bug] Unicode characters are not recognized in linux

### ISSUE THREAD

**Issue by silentrald** [Kylemc1413/SongCore#161]
I have maps/songs that have Japanese Characters on the song title and SongCore does not read the folder names properly as seen in the image below. `Directory.GetDirectories` seems to be the main culprit for this. I'm not sure what C# runtime this uses under the hood but might need help on getting this check. Might ask if this can be resolved within SongCore itself or I might need to replace some dll files within my Beat Saber version to get this working properly.

![image](https://github.com/user-attachments/assets/7c064d93-257d-4c65-b173-3361141550d5)

(Left side compiled in dotnet 8.0.x and `Directory.GetDirectories` seems to work perfectly fine)

Running on Archlinux, X11 compositor.

Some workarounds I had to do was to create a script to rename the folders to remove any Japanese Characters/Unicode so that they could properly be loaded in Beat Saber.

**Comment by Meivyn** [comment]
Beat Saber on its own doesn't officially support Linux. Mods aren't either,  and this specific issue is most likely related to whatever you're using to play the game on Linux.
