### ISSUE TITLE
Custom folders not working - looks like BSM issue, please close.

### ISSUE THREAD

**Issue by unqltango** [Kylemc1413/SongCore#165]
I did set up custom folders about a month ago for my songs and they worked fine. Now they are not recognized. I attached my Folders.xml because the copypasted code gets formatted.
[folders.zip](https://github.com/user-attachments/files/18028152/folders.zip)

Using BSManager, v1.38.0 BS. Steam, W10 Pro 64 bit
Tried with BS 1.29.1 and v1.39.1 BS too, same result.
Please tell me if you need more info.

Edit: I checked if it has something to do with BSManager. I see the songs which are in the official CustomLevels folder, but I don't see any of the custom ones.

Edit 2: It definitely seems like a BSM issue. I copied my custom folders to the v1.38.0 installation and now the custom folders work.

**Comment by Meivyn** [comment]
Do you confirm that it was an issue with BSManager?

**Comment by unqltango** [comment]
Yes, as I wrote in the original post, after I physically copied the custom folders to the BSM 1.38.0 installation folder, the custom song folders started to work again. For some reason BSM can't read anything than the regular customsongs folder from the steam installation. For example the settings for EasyOffset were also stored there and those also had to be copied to the 1.38.0 folder to use.

**Comment by Meivyn** [comment]
Alright, thanks for confirming.
