### ISSUE TITLE
Custom songs with custom colours use the override colours for the trails

### ISSUE THREAD

**Issue by joshjh2002** [Kylemc1413/SongCore#26]
To explain this issue a bit further, when a custom song uses it own custom colours like https://bsaber.com/songs/9a34/, it will set the notes, lights and saber colours to whatever the song has asked to set it to, but the trail colours are set to whatever the in-game overrides are set to and not the colours of the sabers the song has appointed it. This is only an issue with custom songs. I have attached a screenshot that shows what I'm going on about. As you can see, the nots are purple and orange, but the trails are blue and red respectively. 

![unknown](https://user-images.githubusercontent.com/28630084/79878511-6ac0ef80-83e5-11ea-87ce-2dff7493aa00.png)

**Comment by Kylemc1413** [comment]
Already fixed in https://github.com/Kylemc1413/SongCore/commit/ee1325bcacddffd4da4d2b4accf3d8e4901ad5f4 which will be released whenever the next version of SongCore is pushed to BeatMods
