### ISSUE TITLE
fail to add an additional Song Folders

### ISSUE THREAD

**Issue by seophone** [Kylemc1413/SongCore#28]
hello,I follow the direction and fail to add an additional Song Folders
how to make it work？

<folder>
			<Name>SecondSongFolder</Name>
			<Path>C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\SecondSongFolder</Path>
			<Pack>2</Pack>
			<WIP>True</WIP>
		</folder>

**Comment by Kylemc1413** [comment]
Read the readme documentation for the formatt of adding an additional folder
