### ISSUE TITLE
Songs downloaded in the key-id format aren't auto converted in v2.0.4

### ISSUE THREAD

**Issue by jamcar23** [Kylemc1413/SongCore#3]
Songs downloaded in the key-id format get skipped when converting. The path looks like:

`CustomSongs\995-670\[song name]\info.json` 

where `[song name]` is the song name but the converter is trying to find it at 

`CustomSongs\995-670\info.json`. 

Basically, the `-a` flag only looks one subdirectory deep.  This can be fixed by using `-g` and a glob pattern. The unix-like style would be: 

`./songe-converter.exe -k -g '**/info.json' ./CustomSongs/` 

I'm not sure what it is for command prompt but it's probably similar.

**Comment by Kylemc1413** [comment]
SongCore removes the subfolders before runnning the conversion, since the game does not load songs from within subfolders.

**Comment by AyalCiobotaru** [comment]
Haven't played in 3 years and just tried to run the game again after updating all the mods. My songs get converted however the game still isn't reading them. I've tried:

1) Adding a folder entry in folder.xml (this worked as I had some new songs in there and those got loaded)
1) Taking all the converted songs and putting them in Beat Saber/Beat Saber_Data/CustomLevels
1) Restarting, uninstalling and reinstalling Beat Saber and all the mods.

My old songs in json format are still not getting loaded into the game, are those songs just TOO old? Any help would be much appreciated

**Comment by Kylemc1413** [comment]
> Haven't played in 3 years and just tried to run the game again after updating all the mods. My songs get converted however the game still isn't reading them. I've tried:
> 
> 1. Adding a folder entry in folder.xml (this worked as I had some new songs in there and those got loaded)
> 2. Taking all the converted songs and putting them in Beat Saber/Beat Saber_Data/CustomLevels
> 3. Restarting, uninstalling and reinstalling Beat Saber and all the mods.
> 
> My old songs in json format are still not getting loaded into the game, are those songs just TOO old? Any help would be much appreciated

The song converter is no longer bundled with songcore, you'll have to convert the songs yourself and then put them in the correct folder, if they're not getting loaded then they're not valid songs or haven't been converted

**Comment by AyalCiobotaru** [comment]
> > Haven't played in 3 years and just tried to run the game again after updating all the mods. My songs get converted however the game still isn't reading them. I've tried:
> > 
> > 1. Adding a folder entry in folder.xml (this worked as I had some new songs in there and those got loaded)
> > 2. Taking all the converted songs and putting them in Beat Saber/Beat Saber_Data/CustomLevels
> > 3. Restarting, uninstalling and reinstalling Beat Saber and all the mods.
> > 
> > My old songs in json format are still not getting loaded into the game, are those songs just TOO old? Any help would be much appreciated
> 
> The song converter is no longer bundled with songcore, you'll have to convert the songs yourself and then put them in the correct folder, if they're not getting loaded then they're not valid songs or haven't been converted

Ah, songcore only flattens the folder, thought maybe that was enough. Do you have a reference to the old converter that was bundled in songcore?

**Comment by AyalCiobotaru** [comment]
I see that converter.cs is still in master, is that in the latest release? Does that code get run? Do I just need to place "songe-converter.exe" in a specific directory?

**Comment by AyalCiobotaru** [comment]
Is this what I'm going to need https://github.com/lolPants/songe-converter?
