### ISSUE TITLE
Only campain song works, pressing play anywhere else does nothing

### ISSUE THREAD

**Issue by samuelplante1** [Kylemc1413/SongCore#31]
As said in the title, any song in "solo" mode will do nothing when you press on play.
SongCore is active and loads songs when launching, songs are present in "custom songs".

Upon removing the mod, everything works as it should
V 1.11.0

**Comment by samuelplante1** [comment]
So can we have a download for SC v2.9.0? Or separate version tags/files on beatmods.com?
I tried building the dll myself but was missing tons of libraries.

**Comment by Kylemc1413** [comment]
Just update your game?

**Comment by Jangberry** [comment]
1.11.0 is the last update avalable on Steam.
Plus it doesn't solve the issue of miss-labeling on BeatMods. Can it come from an issue during the upload or should someone open an issue on beatmods' git ?

**Comment by Kylemc1413** [comment]
1.11.1 is the last update available on steam. It's not a mislabeling issue on BeatMods, sufficiently close versions in terms of mod compatibility are bundled under the same version, if you were to open ModAssistant like you are meant to for installing mods as a user you would see that the version is labelled as 1.11.1

**Comment by Jangberry** [comment]
Ok @samuelplante1 you probably have the same issue as me: steam isn't showing you the update for beat saber.
To fix it you need to verify the integrity of the game files from steam (I stopped it before the end), then it will show you the update (3.5MB)
And finally ModAssistant will switch from this 
![image](https://user-images.githubusercontent.com/24879004/90987984-902a5980-e58f-11ea-9092-436f84500f71.png) to this 
![image](https://user-images.githubusercontent.com/24879004/90987987-991b2b00-e58f-11ea-8db8-930e4dc8bf15.png)
