### ISSUE TITLE
Can't have more than 6 custom song folders

### ISSUE THREAD

**Issue by WGzeyu** [Kylemc1413/SongCore#44]
![](https://cdn.discordapp.com/attachments/558408020258848789/769182478518059018/unknown.png)

**Comment by KyleM1413** [comment]
That's an issue with the base game not allowing you to scroll through level packs atm

**Comment by Kylemc1413** [comment]
That's an issue with the base game not letting you sroll through level packs within a collection atm

**Comment by wgzeyu** [comment]
Okay, is there any solution?

**Comment by Kyle-Newton** [comment]
https://youtu.be/Bb4YKwmYvWk This is the fix that allows your controller scroll through the playlist folders.

**Comment by Meivyn** [comment]
This has been implemented by the base game.
