### ISSUE TITLE
Can't play some songs since Beat Saber 1.12.2 update

### ISSUE THREAD

**Issue by Kamitachi** [Kylemc1413/SongCore#45]
Since the last update of Beat Saber I'm unable to play some of the songs that I previously could play.
When I select the song and infinite loop start as is trying to load the song but never ends.

Some examples are:
 - https://bsaber.com/songs/eb17/
 - https://bsaber.com/songs/e7d6/
 - https://bsaber.com/songs/9b35/

**Comment by Kylemc1413** [comment]
That sounds like behavior that would happen when you do not have songcore installed

**Comment by Kamitachi** [comment]
It's installed and updated to the version 3.0.1

**Comment by Kylemc1413** [comment]
Can you screenshot the song not loading in game as well as provide the _latest.log file from the Logs folder within the game folder after reproducing the issue?

**Comment by Kamitachi** [comment]
https://imgur.com/a/Pu4iNP0

[_latest.log](https://github.com/Kylemc1413/SongCore/files/5444778/_latest.log)

There you have both the screenshot and the logs.

**Comment by Kylemc1413** [comment]
Yeah both the screenshot and the log confirm that you do not currently have songcore installed

**Comment by Kamitachi** [comment]
Don't know what's happening then.

I deleted the game and all the mods and download everything again, it' seems that now it's working.

Thank you for the help ;)
