### ISSUE TITLE
DirectoryNotFoundException, custom songs not playable v2.0.9

### ISSUE THREAD

**Issue by Corben78** [Kylemc1413/SongCore#5]
Hey there. I'm playing Beat Saber on Linux, which works great thanks to Valve's Proton. Also mods are working great, and I've been playing and even streaming Beat Saber in mixed reality VR now for about 3/4yr on Linux and with mods.

From time to time I have to do a clean install of Beat Saber, especially after a big update, to get mods working again, which causes on Linux that the wine prefix is also deleted and re-created. Since the update to Beat Saber 1.1.0 and the updated mods, I wasn't able to play custom songs any more. They were successfully converted, but the panel to right, where the informations about the song and the play button should occur didn't show up. After tinkering around and having a look into the log files, I realized that a directory couldn't be found, and doesn't seem to be created:
```
[ERROR @ 20:20:35 | IPA] SongCore: System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\users\steamuser\Local Settings\LocalLow\Hyperbolic Magnetism\Beat Saber\SongCoreExtraData.dat".
```
After I created the `LocalLow\Hyperbolic Magnetism\Beat Saber` directory, the needed files of songcore could be created and custom songs where working again.

Looks like Beat Saber itself isn't creating that directory any more, and thus the directory `LocalLow` isn't even created for me. As in the wine prefix no other programs are installed, which might create the `LocalLow` folder, I guess it will never be created after a clean install of Beat Saber, at least on Linux.

Would it be an idea to have the `SongCoreExtraData.dat` file be stored below `Beat Saber\UserData` folder (the games's install folder, where the other mods store they files/configs) instead of being stored below `Local Low`? Or could you create the necessary folders, to make sure they exist?

Thanks in advance!

**Comment by Kylemc1413** [comment]
The reason SongCoreExtraData is stored in the appdata folder is because it's not really meant to be stored with the other mod configs as it's not something the user is meant to see, rather is just data meant to be stored away from where the user would see, as the cached hash data songcore keeps is also stored in that folder. admittedly it never occurred to me that a user might not have the folder where beat saber's save data is stored available. I can look at trying to create that folder if it doesn't exist but can't easily test the creation as I would rather not move/rename/hide enough folders to test creating a folder in that location with permissions etc. Do you know if beat saber stores save data elsewhere on Linux?

**Comment by Corben78** [comment]
For the game or the plugins, it won't matter where Linux stores the files, as wine is reproducing the same file structure as on Windows and encapsulating that in the wine prefix. So any file access on Windows will just be mapped internally to the same location below that wine prefix (which is just a folder itself).

I'll check if Beat Saber changed that folder and is not storing below `LocalLow` anymore. Saving it below that `UserData` folder would just make it independent from that folder. I'd think that only advanced users would tinker with the files there, so I wouldn't matter if they would see the songcore files (and its caching file) there (maybe in a subfolder).

But I'll have a look later at the file structure, maybe it's just Beat Saber having now a new location for its intermediate files. Though I'd expect that users installing Beat Saber for the first time will have the same issue with that missing folder on windows then.

**Comment by Kylemc1413** [comment]
Windows Still actively uses that exact folder for storing player data, which Is why I am confused as to how that exception is occurring if the structure is supposed to be the same

**Comment by Corben78** [comment]
I've found the player data files of Beat Saber in `C:\users\steamuser\AppData\LocalLow\Hyperbolic Magnetism\Beat Saber`, and songcore wants to have its files in `C:\users\steamuser\Local Settings\LocalLow\Hyperbolic Magnetism\Beat Saber`.

So the difference here is `AppData` vs `Local Settings`. I don't know how Beat Saber determines that folder, maybe that changed with an update, as I see in your code you're using a system function (`Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)`) which should be the correct way to get that folder? Or is there a function that would result in the `AppData` folder, instead of the `Local Settings` folder? Maybe it's just a coincidence that this results in the same folder on Windows.

Something must have changed I guess, as it was working before the Beat Saber Update to 1.1.0 without issues. From the git history, I can only see that the file with the code that determines that folder was created on May 18th, so I can't really see how it worked before and I guess you know your code best ;)

Maybe I can hit up the Beat Saber devs and ask how they determine that folder.

**Comment by yshui** [comment]
I'm having this problem as well. And I've seen others who are also experiencing this problem.

Is it possible that Beat Saber changed its directory, and SongCore still works for Windows users because the older folder is not removed?

**Comment by ColonelPanic-42** [comment]
Thank you @Corben78 that was driving me nuts! Seems every time Beat Saber updates it's a major hassle to get everything working again, I wish I could just get Steam to stop forcing me to update.

From what I understand, "Local Settings" is a Windows XP equivalent of either or both of "AppData/Local" and "AppData/LocalLow". I'm pretty sure "LocalLow" should _never_ appear under "Local Settings" though, so whatever is setting this is invalid (whether it's SongCore doing it or Wine getting itself confused somehow). Someone mixing up environment variables maybe?

**Comment by Kylemc1413** [comment]
Considering that this variable is the correct pathing on windows, the settings location for beat saber has also not changed with any of the updates, and that pathing consistently works on windows, I'm inclined to believe it's an issue with wine rather than with songcore

**Comment by Corben78** [comment]
I reached out to Jan “Split” Ilavsky on [twitter](https://twitter.com/Corben78/status/1149305061182443521) and he was so kind to reply to me, how they determine the path within unity:
[Application.persistentDataPath](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html). And I've seen [here](https://answers.unity.com/questions/1144351/cant-find-applicationpersistentdatapath-location.html) that this path already changed with an Engine version change..

I don't know right know which Unity version Beat Saber 1.1.0 is using though.

So can you use the same function in your mod @Kylemc1413 so it would end up either way on the same path?

I haven't checked myself yet, how songcore behaves on a clean Windows install, without that folder existing in the first place. It might also be a mono or dot net issue, that wines uses. That's why my suggestion was to move that folder to the Beat Saber plugin install folder or something similar, so it's independent of that. It wouldn't hurt Windows users, but help Linux gamers. It's of course up to you ;)

**Comment by Kylemc1413** [comment]
Again: The folder beat saber uses to store the data in has not changed in any game version, regardless of they changed how they path to that folder internally, if someone is willing to make a pr to change how songcore locates the folder and can verify it behaves properly on both linux and windows, I'd be glad to accept it, however I do not want to move it to the beat saber install folder as it is not meant to be located with normal mod data

**Comment by yshui** [comment]
A simple solution would be just create it if not found?

**Comment by Kylemc1413** [comment]
Not the preferable solution because then it's in a different place than any of the game's files

**Comment by Kylemc1413** [comment]
Unable to test myself aside from on windows, but made changes for the next version of songcore that will maybe lead to path consistency on linux, will probably release after fixing the mod for the next game update whenever that hits

**Comment by Corben78** [comment]
Thank you very much for looking into this! I'd be happy to test it, if you could provide me a compiled version of the updated version?

**Comment by Kylemc1413** [comment]
The latest public version of songcore for game version 1.3.0 should have the changes now

**Comment by Corben78** [comment]
Though I still have to confirm it thoroughly, I didn't have any issues with custom songs after the update to Beat Saber 1.3.0 and latest SongCore mod. I did a clean install of Beat Saber and its mods, but I didn't have to create any folder manually.
There have been other problems to get mods working at all on Linux, but that's a different [issue](https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/issues/18). Once the mods were working, SongCore didn't cause further issues so far.
Thank you very much!
