### ISSUE TITLE
can see the mod in BS - can´t use ist

### ISSUE THREAD

**Issue by DerBogo** [Kylemc1413/SongCore#50]
I had to reinstall my Beatsaber (V.1.13) and now Songcore isn´t working anymore. I see the Mod in the startscreen and can "click" on it, but if i want to search for a song there is nothing. 

what is wrong?

**Comment by Kylemc1413** [comment]
You're not describing SongCore, so no clue

**Comment by DerBogo** [comment]
When i am playing Beatsaber i can in the start menu clearly sie MODS and SONGCORE - i installed it via modinstaller - but when i click on Songcore Ingame it opens up like usually, but there are no songs listed and if i am searching for a song, there are no results. 

what else i am supposed do describe?

**Comment by Kylemc1413** [comment]
SongCore has no button in game, nor is a More Songs button a part of SongCore
