### ISSUE TITLE
Blocks are reversed

### ISSUE THREAD

**Issue by MusicalPilot** [Kylemc1413/SongCore#55]
For some reason out of nowhere all of my blocks for every song are reversed. Meaning, locks that are normally designated for the right hand are now for the left hand and vice versa. I uninstalled all of my mods and reinstalled them one at a time to find the culprit, and it only began to do this when I installed SongCore. It then stopped doing that immediately after uninstalling SongCore. This is very strange and I've never seen anything like it before. I also don't quite understand how SongCore can do something like that for even the OST songs. This just happened today, though in the middle of a playing session. Everything was fine for the first hour of game play and then all of a sudden everything went reversed and the score board text showed only ampersats (@) and ampersands (&). Beat Saber/mod reinstallation didn't fix it. I also have both the Oculus and Steam versions of Beat Saber installed at the same time (with the same mods) and both experience the same issue. I'm hoping someone else is also experiencing this and/or knows what is happening. I could not find any setting that corresponds to this. 

Thanks!

**Comment by KonKey125** [comment]
I also had this exact issue (down to BeatSaber being fine for the first hour-ish). The strangest thing is that I've looked over [the recent commit](https://github.com/Kylemc1413/SongCore/commit/ddf964c4831caf308b5b6bed356ec4f78927d96e) and the changes implemented shouldn't cause these issues (at least, to the best of my limited understanding).

However, I noticed that the latest commit on GitHub is 3.3.0 and the latest available in the ModLoader is 3.3.1. So something might have happened that we aren't aware of yet.

Anyway, please roll back to a previous version or release a patch.

**Comment by sampepin86** [comment]
Your is not In Left hand mode ?

**Comment by Zoobumafu** [comment]
A friend of mine and I are having the same issue as for 3.2.2, havn't tested the newest version has well,
Chiming in to let you know it is not an isolated case.

**Comment by EnekoT2001** [comment]
Happens to me too, and i cant downgrade bc the moment i open the game it updates itself (confirmed by checking the dll version on the plugins folder, the moment the game loads it updates the file), basically i cant play rn, i cnat uninstall BSPIA bc i need my other mods, this needs fixing asap omg

**Comment by KonKey125** [comment]
> Your is not In Left hand mode ?

Nope. Turning it on or off doesn't have any effect to the game.

**Comment by EnekoT2001** [comment]
Ok i found a fix, just go to your beat saber installation folder, open the folder UserData and delete the folder SongCore. Next time you open the game, SongCore will remake those setting files and everything will be working fine !!

**Comment by Kylemc1413** [comment]
In case you're curious the solution would've been to not be on April 1st, next year I'll try to be more indicative of the cause

**Comment by MusicalPilot** [comment]
Thank you everyone for your insightful comments, and thank you @Kylemc1413 for your solution clarification. Now that I know this is a thing I will be prepared for similar changes in the future. Thanks so much!
