### ISSUE TITLE
BeatSaverDownloader problem

### ISSUE THREAD

**Issue by JacobCavenar** [Kylemc1413/SongCore#57]
I understand that the "more songs" function is part of BeatSaverDownloader but the github for this doesn't have a place to submit issues and I am DESPERATE.

When I click "more songs" it loads forever and I can't download songs. This has been going on for a while and I haven't found a solution for it online. Any idea how to fix this?

**Comment by Kylemc1413** [comment]
Go to the pc-help channel in the beat saber modding group discord if you're having issues with using a mod, not to posting issues on unrelated mods githubs
