### ISSUE TITLE
Unable to download Songs

### ISSUE THREAD

**Issue by SaolGhra** [Kylemc1413/SongCore#60]
I have tried
- Reinstalling the game (includes deleting game files that are kept as well as appdata etc)
- Reinstalling the mods
- Restarting my devices
![OculusScreenshot1628033177](https://user-images.githubusercontent.com/47499708/128099423-ba8dce45-446d-4251-b935-51415ce3a708.jpeg)

**Comment by Kylemc1413** [comment]
SongCore has nothing to do with downloading songs

**Comment by SaolGhra** [comment]
Still though are you aware of any reason this may be happening

**Comment by LudoW809** [comment]
> Still though are you aware of any reason this may be happening

Beatsaver is down

**Comment by SaolGhra** [comment]
ah coolio thanks mate 👍
