### ISSUE TITLE
having problems with this multi select

### ISSUE THREAD

**Issue by midantix** [Kylemc1413/SongCore#63]
so i think its song core because when i go to download a new song in game  it just, doesnt load any new pages and says its because i have "multi select activated" and there is no way to disable it. under that it says no new pages will be loaded and no songs can be downloaded

**Comment by n3tman** [comment]
Hi there. "More Songs" functionality is actually a part of another plugin - [BeatSaverDownloader](https://github.com/Kylemc1413/BeatSaverDownloader).
A pull request that fixes all issues has already been proposed here: https://github.com/Kylemc1413/BeatSaverDownloader/pull/19
I tested it myself (compiled from sources) and it works fine. Multi-select is deactivated if you click this button again (M-S).
For now you need to wait until this PR is checked and merged by BSMG admins. Then it should appear on beatmods.com and in ModAssistant.
