### ISSUE TITLE
[Suggestion] ChroMapper/custom icon for WIP levels

### ISSUE THREAD

**Issue by burritosoftware** [Kylemc1413/SongCore#68]
The current icon for CustomWIPLevels is the MMA2/EditSaber/whatever else icon, and I feel that it should be changed to ChroMapper or have an option to change it to any other icon for preference or to match it up with other editors.

cc: @Caeden117

**Comment by Kylemc1413** [comment]
I don't see why the icon should be changed from the easily recognizable icon of the primary map editor the community has used for the past 2-3 years to one that is less recognizable and will likely confuse many users
