### ISSUE TITLE
How do you add a songs through code?

### ISSUE THREAD

**Issue by Amiron49** [Kylemc1413/SongCore#77]
https://github.com/Kylemc1413/SongCore/commit/457c10783fadd268c8a6d61acd140110531e3185#diff-cbb88464e61276928be0bf0df4cb563b12d7aa35bf11cde6e6675898b5d27234R55

In this commit, [`SongCore.Collections.AddSong`](https://github.com/Kylemc1413/SongCore/commit/457c10783fadd268c8a6d61acd140110531e3185#diff-cbb88464e61276928be0bf0df4cb563b12d7aa35bf11cde6e6675898b5d27234R55) was obsoleted and made an empty stub. And it looks like [`SongCore.Collections.AddExtraSongData`](https://github.com/Kylemc1413/SongCore/commit/457c10783fadd268c8a6d61acd140110531e3185#diff-cbb88464e61276928be0bf0df4cb563b12d7aa35bf11cde6e6675898b5d27234R59) now has the functionality that AddSongData had, but was changed from public to internal. So I SHOULDN'T use this method for adding songs... right? 

Edit: I'm trying to fix/understand [MultiplayerExtensions](https://github.com/Goobwabber/MultiplayerExtensions/) and it seems it relied on AddSong to add songs after downloading them

**Comment by Kylemc1413** [comment]
Extra song data is loaded with the song itself being loaded, which is why those methods are no longer needed

**Comment by Kylemc1413** [comment]
Any downloaded songs will be loaded after refreshing songs if they're in a folder songcore loads songs from

**Comment by Amiron49** [comment]
Gotcha, thanks for clarifying that
