### ISSUE TITLE
[Suggestion] Maintain Dictionary of Hashable, but Broken Beatmaps

### ISSUE THREAD

**Issue by Zingabopp** [Kylemc1413/SongCore#79]
Apparently, there are beatmaps that exist on Beat Saver that are broken, possibly during the conversion process a long time ago (such as the info.dat listing the wrong file extension for the audio file). SongCore discards these songs during the loading process. It would be useful to have a `Dictionary<string hash, string path>` of these songs for mods like PlaylistManager that rely on SongCore to check if a song already exists before downloading them (the broken beatmaps are downloaded over and over).

**Comment by Zingabopp** [comment]
I guess in the case of the audio file having the wrong extension, the beatmap is loaded and playable, but is not included in the hash dictionaries somehow.

**Comment by Kylemc1413** [comment]
Wouldn't it maybe make more sense for beatsaver to just prune/fix unplayable maps since as far as I'm aware it currently wouldn't let maps like that be uploaded anymore

**Comment by Zingabopp** [comment]
It would, although I have no idea how many beatmaps like that exist and fixing them would change the hash. If SongCore is loading the songs and they are playable, they should definitely be in the hash dictionary though.

**Comment by Kylemc1413** [comment]
Isn't the whole point of this that they're not playable as downloaded and not being loaded?

**Comment by Meivyn** [comment]
They are being "loaded" but not playable. There is an "error loading data" error instead, but they *do* show up in the song list.

**Comment by Kylemc1413** [comment]
If they're being loaded but not being properly added to whatever dictionaries downloaders are looking through that could probably just be fixed instead of developing a new dictionary to keep track of those weird maps
