### ISSUE TITLE
[Issue/Bug] Cached WIP levels 

### ISSUE THREAD

**Issue by vaser888** [Kylemc1413/SongCore#80]
1 - Maps in the Cached WIP Levels folder are playable with the "play" button. In the past only "Practice" was clickable but now so is "play". This allows people who are playtesting to accidentally submit to score saber. The regular WIP Levels folder still has the "play" button disabled and works as intended.

2 - Mods like chroma are not being applied to maps in the Cached WIP Levels folder. The "?" on the top right is not present and so no mods are being applied to the map when they are played. The only way for chroma to work in that folder is to unzip the map manually in a folder in the WIP Levels folder. Then the "?" will finally appear in the Cashed WIP Levels folder and the mod will apply to the map when played. If you then delete the folder of the map in WIP Levels, the maps in the Cashed stays the same and you can play it with chroma and the "?" will still be there. 
All maps and mods work as intended in the WIP Levels folder. It's the Cached WIP Levels folder that is having those issues.

**Comment by Kylemc1413** [comment]
Could you please verify this issue exists with no mods installed aside from SongCore and it's dependencies and then upload a log file after reproducing the issue

**Comment by Kylemc1413** [comment]
Scratch that, I know what's probably the issue, I'll investigate and likely push a fix within the next day or two

**Comment by Kylemc1413** [comment]
Should be resolved with SongCore 3.9.1 once that is pushed to ModAssistant

**Comment by vaser888** [comment]
Alright, Thanks. 

If you need anything, just let me know.
