### ISSUE TITLE
Highscore Missing

### ISSUE THREAD

**Issue by MasterRedStorm** [Kylemc1413/SongCore#82]
When installing SongCore all (Group) Scores of Custom Maps are empty.
I´ve read online that once LocalScoreFixer could fix that. But that dosnt work anymore and its not maintained anymore.

How can i keep my score which was build up for over a year now?

**Comment by Kylemc1413** [comment]
When songcore is installed levels have different levelids compared to the base game, any external local tools to convert base game scores to what their songcore levelids would be should still work if they were made within the past couple of years and your song library is the same as when those scores were set

**Comment by Meivyn** [comment]
I highly suggest not doing that now that the game uses dictionaries (as of game version 1.33.0), as this could result in the player's data being wiped, in case anyone goes through this issue.
