### ISSUE TITLE
[Suggestion] Split the "Allow Custom Song Colors" into settings for block colors and lighting colors

### ISSUE THREAD

**Issue by TheBlackParrot** [Kylemc1413/SongCore#99]
I still want to allow maps to change the lighting colors, while forcing colors only on the blocks. The only way I have of forcing block colors is to turn off the "Allow Custom Song Colors" setting, but that also forces the lighting color to my own defined scheme. Can we get this setting split in two?

**Comment by Mawntee** [comment]
Bumping this. 
Mappers and lighters put so much effort into lighting, yet I usually have custom colours off due to being colour blind and having a hard time reading some custom note colours set by the mappers. I'd love to still experience the intended lightshows though!
